- name: Configuring repo 
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{ component }}
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    name: mongod
    enabled: true

- name: Configuring hostname for {{ component }}
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}