- name: Configuring nginx124
  ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Vault-prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: vault-prereq

- name: copying nginx proxy file
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ proxy_path }}"

- name: Clearning old {{ component }} content
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Creating {{ component }} directoru
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

- name: Downloading {{ component }} content
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ app_path }}"
    remote_src: yes


- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: nginx
    enabled: true

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname