- name: Configuring repo 
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Installing {{ component }}
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3 install hvac

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: rabbitmq-server
    enabled: true

- name: Provisioning RabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: "{{ app_user}}"
    password: "{{ secrets.rabbitmq_pass }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname