- name: Installing {{ component }}
  ansible.builtin.dnf:
    name: mysql-server
    state: present
    
- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mysqld
    enabled: true

- name: Configuring {{ component }} root password 
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{secrets.root_password}} || true 

- name: Configuring hostname for {{ component }}
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }} || true
