- name: Installing {{ component }}
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Vault-prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: vault-prereq

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mysqld
    enabled: true

- name: Resetting {{ component }} root password 
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.mysql_pass }} || true 

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname