- name: Configuring mongodrepo 
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongoshell
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Injecting schema 
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.clouding-app.shop </app/db/master-data.js