- name: Installing mysql shell
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Injecting schema 
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{ env }}.clouding-app.shop -u{{ secrets.mysql_user }} -p{{ secrets.mysql_pass }} < /app/db/{{ item }}.sql
  when: setup_schema is defined