component: rabbitmq
app_user: roboshop
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/rabbitmq token={{ token }} url=https://vault.clouding-app.shop:8200  validate_certs=False') }}"